PAGE/mysite/capstone/urls.py
from django.urls import path

from . import views
from . import step



from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'capstone'

urlpatterns = [

    path('', views.main, name='main'),
    path('demo_intro/', views.demo_intro, name='intro'),
    path('demo_practice/', views.demo_practice, name='practice'),
    path('demo_upload/', views.demo_upload, name='upload'),
    path('demo_history/', views.demo_history, name='history'),
    path('demo_extract', views.demo_extract, name='extract'),
    path('demo_film/', views.demo_film, name='film'),
    path('demo_score/', views.demo_score, name='score'),
    # path('practice/', finaltest.testmain, name='practice'),
    #path('practice/', views.practice, name='practice'),




    #path('demo_practice/<str:songname>/', step.practice_detail, name='songpractice'),
    
    # 원래 있는 파일
    path('demo_practice/<str:songname>/step1/', step.step1main,name = 'step1' ),
    path('demo_practice/<str:songname>/step2/', step.step2main,name = 'step2' ),
    # path('demo_practice/<str:songname>/step3/', step.step3main,name = 'step3' ),

    # 업로드 할 때
    path('demo_practice/C:/fakepath/<str:songpath>/choosenum/', step.choosenum ), # 파일 업로드 하고 누르면 해당 파일 정보를 가지고 몇명을 선택할 지 선택하는 창
    
    # 업로드 후 1인이라고 할 때
    path('demo_practice/<str:songname>/userinput/step1/', step.userstep1main, name = 'userstep1' ),
    #path('practice/C:/fakepath/<str:songpath>/choosenum/', step.choosenum ),
    # path('practice/userinput/chooseperson/', step.chooseperson ),
    # path('practice/userinput/1/getsong/', step.practice ),

    # 업로드 후 2인이라고 할 때 crop
    path('demo_practice/<str:songname>/crop/', step.cropping, name = 'crop_and_extract' ),
    path('demo_practice/<str:songname>/demo_score/', step.step2main, name = 'demo_score'),
    path('demo_practice/<str:songname>/<int:num>/', step.extract, name = 'extract' ),



    #path('demo_practice/<str:songname>/<int:peoplenum>/', step.practice_detail, name = 'step0'),



]

PAGE/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
#from pybo import views

urlpatterns = [
    path('anmu/', include('capstone.urls')), #capstone project



    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # project의 성격이므로
    path('common/', include('common.urls')),
    #http://localhost:8000/ 을 입력했을 때 바로 pybo.urls 로 가게 함
]

PAGE/mysite/pybo/urls.py
from django.urls import path
from . import views
app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:team_id>/', views.teamDetail, name='detail'),
    path('team/create/<int:team_id>/', views.teamCreate, name='team_create')

    # path('camera/',camera.
]

PAGE/mysite/capstone/models.py
from django.db import models

# Create your models here.


class DanceInfo(models.Model):  # information of every song
    song = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    content = models.TextField()  # coord info
    time = models.CharField(max_length=50)  # play time

    def __str__(self):
        return self.song + " - " + self.artist


class Team(models.Model):
    teamName = models.CharField(max_length=100)

    def __str__(self):
        return self.teamName


class TeamMember(models.Model):
    # Team 전체를 받는다
    teamName = models.ForeignKey(Team, on_delete=models.CASCADE)
    memberName = models.CharField(max_length=100)

    def __str__(self):
        return self.teamName.teamName + " - " + self.memberName


class User(models.Model):
    playerName = models.CharField(max_length=20)
    user_id = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.playerName


class Record(models.Model):  # record
    song = models.CharField(max_length=200)
    score = models.IntegerField()

    def __str__(self):
        return self.song + '-' + str(self.score )

PAGE/mysite/capstone/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse
from .models import *

from subprocess import run, PIPE
import sys
app_name = 'capstone'


def main(request):
    # return render(request, 'capstone/test1.py')
    return render(request, 'capstone/demo_intro.html')


def demo_intro(request):
    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_intro.html')

# def practice(request):
#     # return HttpResponse("Hello world")
#     return render(request, 'capstone/practice.html')


def demo_practice(request):
    song_list = DanceInfo.objects.order_by('song')

    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_practice.html', context={'song_list': song_list})

def demo_upload(request):
    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_upload.html')

def demo_history(request):
    record_list = Record.objects.order_by() # Team.objects.all()
    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_history.html',{'record_list': record_list})

def demo_extract(request):
    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_extract.html')

def demo_film(request):
    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_film.html')

def demo_score(request, songname):
    # return HttpResponse("Hello world")
    return render(request, 'capstone/demo_score.html')


# def team(request):
#     team_list = Team.objects.order_by('teamName') # Team.objects.all()
#     context = {'team_list': team_list}
#     return render(request, 'capstone/team.html', context)
#     # return render(request, 'capstone/team.html')


# def songlist(request):
#     song_list = DanceInfo.objects.order_by('song')
#     context = {'song_list': song_list}
#     return render(request, 'capstone/songlist.html', context)






# def practice(request):
#     song_list = DanceInfo.objects.order_by('song')
#     context = {'song_list': song_list}
#     # inp = request.POST.get('param')
#     # out = run([sys.executable, './test1.py',inp], shell = False, stdout=PIPE)
#     # print(out)

#     #return render(request, 'capstone/practice.html')
#     return render(request, 'capstone/practice.html', context)








# def step1(request, songname):
#     aa = str(songname)
#     #return HttpResponse( songname)
#     return render (request, 'capstone/step1.html', {'song' : songname})

# def step2(request, songname):
#     aa = str(songname)
#     #return HttpResponse( songname)
#     return render (request, 'capstone/step2.html', {'song' : songname})

# def step3(request, songname):
#     aa = str(songname)
#     # return HttpResponse( songname)
#     return render (request, 'capstone/step3.html', {'song' : songname})





# def record(request):
#     return render(request, 'capstone/record.html')


# def mypage(request):
#     return render(request, 'capstone/mypage.html')


# def waiting(request):
#     return render(request, 'capstone/waiting.html')

# if __name__ = "__main__":
#     print('main')

# def main(request):
#     return mypage(request)

PAGE/mysite/templates/capstone/demo_extract.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
	<head>
		<title>Extract - CAU CAPSTONE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
            <a href="{% url 'capstone:main' %}demo_intro" class="logo"><strong>중앙대 캡스톤</strong> <span>by 중안연가</span></a>
					</header>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="{% static 'images/pic07.jpg' %}" alt="" />
							</span>
							<header class="major">
								<h1>Extract</h1>
							</header>
							<div class="content">
								<p>PICK SOMEONE YOU WILL FOLLOW.<br />
								CHOOSE 1 OR 2 !</p>
                <form>
                  <ul class="actions">
                    <input type="button" value="LEFT" onclick="location.href = '{% url 'capstone:practice' %}{{song}}/1/'" style="margin-left : 20px">
                    <input type="button" value="RIGHT" onclick="location.href = '{% url 'capstone:practice' %}{{song}}/2/'" style="margin-left : 10px">
                  </ul>
                </form>
							</div>
						</div>
					</section>



			</div>

			<!-- Scripts -->
				<script src="{% static 'assets/js/jquery.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'assets/js/browser.min.js' %}"></script>
				<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
				<script src="{% static 'assets/js/util.js' %}"></script>
				<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

PAGE/mysite/templates/capstone/demo_film.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
	<head>
		<title>Filming - CAU CAPSTONE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
            <a href="{% url 'capstone:main' %}demo_intro" class="logo"><strong>중앙대 캡스톤</strong> <span>by 중안연가</span></a>
					</header>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="{% static 'images/pic07.jpg' %}" alt="" />
							</span>
							<header class="major">
								<h1>Filming</h1>
							</header>
							<div class="content">
								<p>촬영중입니다. 잠시만 기다려주세요<br />
								모든 창이 꺼지면 점수보기 버튼을 눌러주세요.</p>
								<ul class="actions">
										<li><a href="{% url 'capstone:practice' %}{{song}}/demo_score/" class="button next scrolly">점수 보기</a></li>
								</ul>
							</div>
						</div>
					</section>
			</div>
			<!-- Scripts -->
				<script src="{% static 'assets/js/jquery.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'assets/js/browser.min.js' %}"></script>
				<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
				<script src="{% static 'assets/js/util.js' %}"></script>
				<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

PAGE/mysite/templates/capstone/demo_history.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
	<head>
		<title>History - CAU CAPSTONE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
				<!-- Note: The "styleN" class below should match that of the banner element. -->
        <header id="header">
          <a href="{% url 'capstone:main' %}demo_intro" class="logo"><strong>중앙대 캡스톤</strong> <span>by 중안연가</span></a>
        </header>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="{% static 'images/pic07.jpg' %}" alt="" />
							</span>
							<header class="major">
								<h1>History</h1>
							</header>
							<div class="content">
								<p>아래의 기록들을 통해<br />
                  당신의 기록을 확인하세요!</p>
								<ul class="actions">
										<li><a href="#one" class="button next scrolly">기록 보기</a></li>
								</ul>
							</div>
						</div>
					</section>

          <!-- Main -->
  					<div id="main" class="alt">

  						<!-- One -->
  							<section id="one">
  								<div class="inner">
  									<header class="major">
  										<h3>기록</h3>
  									</header>



										{% if record_list %}
										<ul>
										{% for record in record_list %}
											<p style = "font-size :20px;">{{ record.song }} , {{ record.score }}</p>
										{% endfor %}
										</ul>
										{% else %}
											<p>노래가 없습니다.</p>
										{% endif %}
<!--
  									<p>YEJI - River : 87.32</p>
  									<p>xxx - Person_back : 98.93</p> -->











  								</div>
  							</section>

  					</div>

					<!-- Footer -->
							<footer id="footer">
									<div class="inner">
											<ul class="icons">



													<li><a href="https://github.com/2021-2-Capstone-Design/Capstone-Design" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>

											</ul>
											<ul class="copyright">
													<li>Chungang Univ.</li><li>Team: <a>Capstone Design #6</a></li>
											</ul>
									</div>
							</footer>
			</div>

			<!-- Scripts -->
				<script src="{% static 'assets/js/jquery.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'assets/js/browser.min.js' %}"></script>
				<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
				<script src="{% static 'assets/js/util.js' %}"></script>
				<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

PAGE/mysite/templates/capstone/demo_practice.html
<!DOCTYPE HTML>
<!--
   Forty by HTML5 UP
   html5up.net | @ajlkn
   Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
   <head>
      <title>Practice - CAU CAPSTONE</title>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
      <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
      <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
   </head>
   <body class="is-preload">

      <!-- Wrapper -->
         <div id="wrapper">

            <!-- Header -->
            <!-- Note: The "styleN" class below should match that of the banner element. -->
        <header id="header">
          <a href="{% url 'capstone:main' %}demo_intro" class="logo"><strong>중앙대 캡스톤</strong> <span>by 중안연가</span></a>
        </header>

            <!-- Banner -->
            <!-- Note: The "styleN" class below should match that of the header element. -->
               <section id="banner" class="style2">
                  <div class="inner">
                     <span class="image">
                        <img src="{% static 'images/pic07.jpg' %}" alt="" />
                     </span>
                     <header class="major">
                        <h1>Practice</h1>
                     </header>
                     <div class="content">
                        <p>제공하는 안무를 연습해봐요!<br />
                        당신이 원하는 안무를 추가해보세요!</p>
                        <ul class="actions">
                              <li><a href="#two" class="button next scrolly">안무 리스트 보기</a></li>
                        </ul>
                     </div>
                  </div>
               </section>

            <!-- Main -->
               <div id="main">

                     <!-- One -->
                        <section id="one">
                           <div class="inner">
                              <header class="major">
                                 <h2>UPLOAD VIDEO</h2>
                              </header>
                              <p>따라하길 원하는 영상을 직접 추가해 주세요.</p>
                              <form>
                                 <ul class="actions">
                                    <li><input type = "file"  accept="mp4" name="param"></li>
                                 </ul>
                                 <ul class="actions">
                                    <li><input type = "button" value = "UPLOAD VIDEO" onclick="location.href = '{% url 'capstone:practice' %}' + param.value + '/choosenum/'" ></li>
                                 </ul>
                              </form>
                           </div>
                        </section>



                  <!-- Two -->
                     <section id="two" class="spotlights">

                        {% if song_list %}
                        <!-- <ul> -->
                        {% for song in song_list %}
                              <!-- <li><a href="{% url 'capstone:practice' %}{{ song.song }}/">{{ song.song }} , {{ song.artist }}, {{ song.time }}</li> -->

                           <section>





                              <a href="{% url 'capstone:practice' %}{{ song.song }}/step1/" class="image">

                                 <img src="{% static 'images' %}/{{ song.song }}.jpg" alt="" data-position="center center" />



                              </a>




                              <div class="content">
                                 <div class="inner">
                                    <!-- <header class="major"> {{ song.song }} , {{ song.artist }}, {{ song.time }} -->
                                       <h3>{{ song.artist }} - {{ song.song }}</h3>
                                    </header>
                                    <p>Video Runtime = {{ song.time }}</p>
                                    <ul class="actions">
                                       <li><a href="{% url 'capstone:practice' %}{{ song.song }}/step1/" class="button">Play Video</a></li>
                                    </ul>
                                 </div>
                              </div>
                           </section>










                        {% endfor %}
                        <!-- </ul> -->
                        {% else %}
                              <p>노래가 없습니다.</p>
                        {% endif %}


                        <!-- <section>
                           <a href="generic.html" class="image">
                              <img src="{% static 'images/person_back.jpg' %}" alt="" data-position="center center" />
                           </a>
                           <div class="content">
                              <div class="inner">
                                 <header class="major">
                                    <h3>xxx - Person_back</h3>
                                 </header>
                                 <p>Video Runtime = 0:04 sec</p>
                                 <ul class="actions">
                                    <li><a href="generic.html" class="button">Play Video</a></li>
                                 </ul>
                              </div>
                           </div>
                        </section>





                        <section>
                           <a href="generic.html" class="image">
                              <img src="{% static 'images/river.jpg' %}" alt="" data-position="top center" />
                           </a>
                           <div class="content">
                              <div class="inner">
                                 <header class="major">
                                    <h3>YEJI - River</h3>
                                 </header>
                                 <p>Video Runtime = 0:05 sec</p>
                                 <ul class="actions">
                                    <li><a href="generic.html" class="button">Play Video</a></li>
                                 </ul>
                              </div>
                           </div>
                        </section> -->






                        <!-- more ? -->
                        <!-- <section>
                           <a href="generic.html" class="image">
                              <img src="images/pic10.jpg" alt="" data-position="25% 25%" />
                           </a>
                           <div class="content">
                              <div class="inner">
                                 <header class="major">
                                    <h3>Sed nunc ligula</h3>
                                 </header>
                                 <p>Nullam et orci eu lorem consequat tincidunt vivamus et sagittis magna sed nunc rhoncus condimentum sem. In efficitur ligula tate urna. Maecenas massa sed magna lacinia magna pellentesque lorem ipsum dolor. Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis tempus.</p>
                                 <ul class="actions">
                                    <li><a href="generic.html" class="button">Learn more</a></li>
                                 </ul>
                              </div>
                           </div>
                        </section> -->
                     </section>

               </div>





               <!-- Footer -->
                     <footer id="footer">
                           <div class="inner">
                                 <ul class="icons">



                                       <li><a href="https://github.com/2021-2-Capstone-Design/Capstone-Design" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>

                                 </ul>
                                 <ul class="copyright">
                                       <li>Chungang Univ.</li><li>Team: <a>Capstone Design #6</a></li>
                                 </ul>
                           </div>
                     </footer>
         </div>

      <!-- Scripts -->
         <script src="{% static 'assets/js/jquery.min.js' %}"></script>
         <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
         <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
         <script src="{% static 'assets/js/browser.min.js' %}"></script>
         <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
         <script src="{% static 'assets/js/util.js' %}"></script>
         <script src="{% static 'assets/js/main.js' %}"></script>

   </body>
</html>

PAGE/mysite/templates/capstone/demo_score.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
	<head>
		<title>Score - CAU CAPSTONE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
            <a href="{% url 'capstone:main' %}demo_intro" class="logo"><strong>중앙대 캡스톤</strong> <span>by 중안연가</span></a>
					</header>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="{% static 'images/pic07.jpg' %}" alt="" />
							</span>
							<header class="major">
								<h1>Score {{score}}</h1>
							</header>
							<div class="content">
								<p>수고하셨어요!<br />
							  아래 기록을 확인하세요!</p>
								<ul class="actions">
									<li><a href="{% url 'capstone:main' %}demo_intro/" class="button next scrolly">메인으로 돌아가기</a></li>
								</ul>
							</div>
						</div>
					</section>

				<!-- Main -->
					<div id="main" class="alt">

						<!-- One -->
							<section id="one">
								<div class="inner">
									<header class="major">
										<h3>{{song}}</h3>
									</header>
									<h3>틀린 부위 및 타임스탬프</h3>
									{% if comment_list %}
									<ul>
									{% for comment in comment_list %}
										<p>{{comment}}</p>
											<!-- <li><a href="{% url 'capstone:practice' %}{{ song.song }}/">{{ song.song }} , {{ song.artist }}, {{ song.time }}</li> -->
									{% endfor %}
									</ul>
									{% else %}
											<p>틀린 부위가 없습니다</p>
									{% endif %}

<!--
									<p>틀린 부위 및 타임스탬프1</p>
									<p>틀린 부위 및 타임스탬프2</p>
									<p>총점</p> -->
								</div>
							</section>

					</div>

					<!-- Footer -->
							<footer id="footer">
									<div class="inner">
											<ul class="icons">



													<li><a href="https://github.com/2021-2-Capstone-Design/Capstone-Design" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>

											</ul>
											<ul class="copyright">
													<li>Chungang Univ.</li><li>Team: <a>Capstone Design #6</a></li>
											</ul>
									</div>
							</footer>
			</div>

			<!-- Scripts -->
				<script src="{% static 'assets/js/jquery.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'assets/js/browser.min.js' %}"></script>
				<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
				<script src="{% static 'assets/js/util.js' %}"></script>
				<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

PAGE/mysite/templates/capstone/demo_upload.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
	<head>
		<title>Upload - CAU CAPSTONE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
            <a href="{% url 'capstone:main' %}demo_intro" class="logo"><strong>중앙대 캡스톤</strong> <span>by 중안연가</span></a>
					</header>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="{% static 'images/pic07.jpg' %}" alt="" />
							</span>
							<header class="major">
								<h1>Upload</h1>
							</header>
							<div class="content">
								<p>1인 영상인지 2인 영상인지 선택해주세요!</p>
							</div>
						</div>
					</section>

				<!-- Main -->
					<div id="main" class="alt">

						<!-- One -->
							<section id="one">
								<div class="inner">
									<form>
										<ul class="actions">
											<input type="button" value="Video with ONE Person" onclick="location.href = '{% url 'capstone:practice' %}{{song}}/userinput/step1/'">
										</ul>
										<ul class="actions">
										  <input type="button" value="Video with TWO People" onclick="location.href = '{% url 'capstone:practice' %}{{song}}/crop/'">
										</ul>
									</form>
								</div>
							</section>

					</div>

					<!-- Footer -->
							<footer id="footer">
									<div class="inner">
											<ul class="icons">



													<li><a href="https://github.com/2021-2-Capstone-Design/Capstone-Design" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>

											</ul>
											<ul class="copyright">
													<li>Chungang Univ.</li><li>Team: <a>Capstone Design #6</a></li>
											</ul>
									</div>
							</footer>
			</div>

			<!-- Scripts -->
				<script src="{% static 'assets/js/jquery.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'assets/js/browser.min.js' %}"></script>
				<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
				<script src="{% static 'assets/js/util.js' %}"></script>
				<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>